# Schema for the configuration files of the custom_config module.
custom_config.settings:
  type: config_object
  label: 'custom_config settings'
  mapping:
    example:
      type: string
      label: 'Example'
